name: Deploy on PR merge to main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan loarwenn.ventsdouest.dev >> ~/.ssh/known_hosts

    - name: Pull latest code on server
      run: |
        ssh debian@loarwenn.ventsdouest.dev << 'EOF'
          cd /dossier/vers/le/repo
          sudo git pull origin main
        EOF
